FROM node:10

WORKDIR /usr/src/app

COPY ./package.json .

RUN yarn install --production

COPY ./dist ./
COPY ./.env.example ./.env
COPY ./ormconfig.json .

RUN ls

ENV NODE_ENV production

EXPOSE 4000

CMD ["node", "server.js"]